[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
padding = { x = 7, y = 7 }
opacity = 0.9
blur = true

[cursor]
style = { shape = "Block", blinking = "Never" }

[scrolling]
history = 100000

[font]
size = 14.0
normal = { family = "Berkeley Mono", style = "Regular" }
bold = { family = "Berkeley Mono", style = "Bold" }
italic = { family = "Berkeley Mono", style = "Italic" }
bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }

[bell]
animation = "EaseOutExpo"

[debug]
log_level = "Info"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[general]
# ~/.config/alacritty/themes: https://github.com/alacritty/alacritty-theme
# enfocado_dark
# github_dark_tritanopia p
# pastel_dark
# rose_pine_moon

import = [
    "~/.config/alacritty/themes/themes/rose_pine_moon.toml"
]
